"""add anime and series tables 2

Revision ID: 3388a6484fe5
Revises: 9b6c2a5fda0c
Create Date: 2025-03-09 18:55:45.009273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3388a6484fe5'
down_revision: Union[str, None] = '9b6c2a5fda0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('posters', sa.String(length=200), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('in_favorites', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('preview', sa.String(length=200), nullable=True),
    sa.Column('fhd_url', sa.String(length=200), nullable=True),
    sa.Column('hd_url', sa.String(length=200), nullable=True),
    sa.Column('sd_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    op.drop_table('anime')
    # ### end Alembic commands ###
